name: movie-frontend-workflow
run-name: build and upload compressed build artifact

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: checkout ui repository
        uses: actions/checkout@v4
        with:
          path: main
      - name: get node.js 
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: install project dependencies
        working-directory: ${{github.workspace}}/main
        run: npm install

      - name: create minified build
        working-directory: ${{github.workspace}}/main
        run: npm run build

      - name: create compressed build
        working-directory: ${{github.workspace}}/main/dist
        run: tar -czvf ../${{ github.sha }}.tar .

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}_build
          path: '${{github.workspace}}/main/${{ github.sha }}.tar'

